[theme]
primaryColor="#4B98FF"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="monospace"

[client]
showErrorDetails="type"
toolbarMode="minimal"

[server]
port=8501
headless=true
fileWatcherType="none"
maxUploadSize=50
enableStaticServing=false

[browser]
gatherUsageStats=true
