[theme]
primaryColor="#4B98FF"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="monospace"

[client]
showErrorDetails="type"
toolbarMode="minimal"

[server]
fileWatcherType="none"
maxUploadSize=50

[browser]
gatherUsageStats=false
